dataset:
  train_path: /content/data/train
  val_path: /content/data/val

training:
  epochs: 50
  batch_size: 16
  img_size: 640
  learning_rate: 0.001

model:
  name: yolov8n.pt
  save_path: runs/train

inference:
  conf_threshold: 0.3
  imgsz: 640
